name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: production

jobs:
  deploy:
    environment: ${{ github.event.inputs.environment || 'production' }}
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |

            PROJECT_DIR="${{vars.PROJECT_DIR}}"


            if [ -d "$PROJECT_DIR" ]; then
              echo "Directory exists, pulling latest changes..."
              cd "$PROJECT_DIR"
              git pull origin main
            else
              echo "Directory does not exist, cloning repository..."
              git clone git@github.com:${{ github.repository }} "$PROJECT_DIR"
              cd "$PROJECT_DIR"
            fi

            if docker compose ps | grep -q "static-server"; then
              echo "Container is running, restarting..."
              docker compose down
              docker compose up -d
            else
              echo "Container is not running, starting..."
              docker compose up -d
            fi
